# docker-compose.yml
version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true  # важно для запуска QEMU и Docker внутри контейнера
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: